.gitmodules, .travis.yml
* Update submodules to use `https://` instead of `git://`
* Describe `.travis.yaml`
* Greater transparency (previously used privately hosted travis-ci.com)
@goruha
=> Use travis-ci.org

rootfs/opt/geodesic
* Add a new `uninstall` command to uninstall geodesic
* Make it easy to test geodesic and then uninstall without leaving any artifacts laying around
* Does not delete `~/.geodesic` folder
@goruha
=> Add uninstall target for geodesic shell

rootfs/etc/profile.d/defaults.sh, rootfs/etc/profile.d/iterm.sh, rootfs/opt/geodesic
* Display brand-able terminal description that defaults to "Geodesic"
* Make it more clear that you're in a Geodesic shell
* Only works in `iTerm.app` (which is the most common 3rd party terminal app for OSX; typically used by power users)
@goruha
=> iTerm Integration

rootfs/etc/profile.d/prompt.sh
* `source` a cluster-specific `.bashrc` file if one exists had hasn't already been loaded
* make it easier to define cluster-specific shortcuts or aliases (E.g. `alias cloudposse=kubectl --namespace=cloudposse`)
@goruha
=> Load a cluster-specific .bashrc file if one exists

Dockerfile
* Add AWS Elastic Beanstalk Client (`eb`)
https://pypi.python.org/pypi/awsebcli/3.10.1
* EB Command Line Interface (CLI) is a tool that helps you deploy and manage your AWS Elastic Beanstalk applications and environments. It also provides integration with Git for easy Heroku-like deployment
=> Add Elastic Beanstalk CLI 3.10.1

rootfs/usr/local/include/toolbox/config/Makefile
* Use AWS_IAM_ROLE_ARN variable
* Wrong variable name was used and it broke mounting of buckets when assumed roles were used
=> Fix `cloud config mount` with Assumed Roles

rootfs/usr/local/include/terraform/init
* Changed AWS_ASSUME_ROLE_ARN to AWS_IAM_ROLE_ARN
* After support profiles we need to fix terraform init
=> Fix terraform config init with assumed roles

rootfs/usr/local/include/toolbox/kops/Makefile.defaults
* Made kops respect default `AWS_REGION`
* When I specify default region for profile, I want kops to use it as default also
=> Made kops respect default AWS_REGION

Dockerfile
* Disable IPv6 
* Fix helm error `E0702 16:53:48.804933     363 portforward.go:209] Unable to create listener: Error listen tcp6 [::1]:37117: bind: cannot assign requested address`
=> Disable IPv6 for Helm Support

rootfs/usr/local/include/toolbox/config/Makefile
- fix typo in `toolbox/config` Makefile
- fix command `cloud config reset`
=> typo fix in 'cloud config reset' command

rootfs/etc/profile.d/defaults.sh, rootfs/etc/profile.d/prompt.sh
* Removed all references to CLOUD_CONFIG and CLOUD_CONFIG_SAMPLE vars.
* These vars are not used anymore in the new geodesic version with Docker inheritance.
=> Removed all references to CLOUD_CONFIG and CLOUD_CONFIG_SAMPLE vars

README.md
* Fixed `geodesic use --name=aws.example.com` in README.md.
* `geodesic use` command requires `name` parameter in the format `--name=aws.example.com`.
=> Fix README regarding `geodesic use`

rootfs/etc/profile.d/user.sh, rootfs/opt/geodesic
* Added script `user.sh` which creates the user with name `${USER}` if it does not exist in the container.
* The main goal is to create the user based on environment variable `${USER}` in the container.
* If the local user does not exist, this causes an error with use Ansible
=> Add Support for Native `USER`

rootfs/etc/ssh/ssh_config
* Added `/etc/ssh/ssh_config` and disabled `StrictHostKeyChecking`
* When you run Ansible, it is easy to miss host key confirmation request: `Are you sure you want to continue connecting (yes/no)?`
=> Disable SSH Strict Host Key Checking

rootfs/etc/profile.d/use-profile.sh
* Check if AWS configs exist before attempting to call `use-profile`
* See: https://github.com/cloudposse/geodesic/issues/73
* Without this fix, if AWS cli was not configured, the shell would immediately exit
* Bug affected new users (cold-start problem)
=> Only use-profile if AWS configured

rootfs/etc/profile.d/locale.sh, rootfs/etc/profile.d/prompt.sh, rootfs/usr/local/include/terraform/apply
* Use special `bash` 3.2+ feature for outputting `utf8` characters (`$'\uXXXX'`)
* Explicitly set locale (sorry, hardcoded to `en_US.utf8`)
* This seems to fix the prompt line wrapping problems
* `\[....\]` does not help with `utf8` characters (only `ansi`)
=> Fix utf-8 prompt

.gitmodules, Dockerfile, Makefile
* Drop the git submodule for `aws-assumed-role`
* Install script the way we do all of our other dependencies
* Consistency
* Submodules add undo complexity
=> Install aws-assumed-role with curl

Dockerfile, rootfs/usr/local/include/toolbox/config/Makefile
* Sleep until `/mnt/remote` is mounted
* Remove the `VOLUME` for `/mnt/remote`
* Previous command is run in the background 
* Need to operate asynchronously as we don't know when the filesystem will be mounted
* The `VOLUME` statement caused `/mnt/remote` to always report as `mountpoint` even if it was not mounted
=> Block Until Filesystem Mounted

Dockerfile
* Disable the vim swapfile
* It fails when files exist on `goofys`
=> Disable vim swap file

rootfs/templates/wrapper
* Use an optimistic strategy to select a port at random using the the current pid (`$$`) offset by `30000`
* Support concurrent geodesic sessions
=> Avoid port conflicts

rootfs/usr/local/bin/cloud
* Check for existence of a `/conf/$module/Makefile`
* the previous check broke if the directory exists (e.g. `/conf/kops/manifest.yaml`) and no Makefile
=> Check for Makefile Module

Dockerfile
* Pin `awscli` to `1.11.185`
* Reorgzanize installation of dependencies
* Drop `--upgrade` on `pip` install
* Reduce verbosity on `tar` for `gcloud` install
* Need stable AWS Cli. Currently `1.12` appears to break our `aws-assumed-role` implementation
* Using `--upgrade` on `pip install` defeats the purpose on version pinning
* Changed order of package installs to ensure that `awscli==$AWSCLI_VERSION` is installed
=> Pin version of AWS Cli to 1.11.185

rootfs/etc/profile.d/defaults.sh
* namespace terraform remote state based on your current working directory
* Support multiple terraform projects with state separated by directory (`pwd`)
State has moved to `s3://$bucket/geodesic/terraform/$project` where `project` is your current working directory
Rough upgrade steps:
```
cd /conf/tf
cloud config mount
mkdir -p /mnt/remote/geodesic/terraform/$(basename `pwd`)
mv /mnt/remote/geodesic/terraform/*.tfstate /mnt/remote/geodesic/terraform/$(basename `pwd`)
```
=> Support multiple projects (breaking change)

rootfs/etc/profile.d/defaults.sh
* Fix `HELM_HOME` env var
* On docker build helm plugins installed into directory that are not used later
=> Fix HELM HOME

Dockerfile
* Bump terraform version to `0.11.2`
* Bug fixes and new features
* https://github.com/hashicorp/terraform/blob/v0.11.2/CHANGELOG.md
=> Bump terraform version to `0.11.2`

Dockerfile
* Add `github-commenter`
* To send the output from other programs as GitHub comments on Commits, Pull Request Reviews or Issues
```sh
terraform plan 2>&1 | github-commenter -format "Output from `terraform plan`<br/>```{{.}}```"
```
=> Add `github-commenter`

Dockerfile, rootfs/etc/profile.d/aws-vault.sh, rootfs/etc/profile.d/prompt.sh
* Add support for `aws-vault server` mode
* Support endless sessions for local development by mocking EC2 metadata api
=> Add support for aws-vault server mode

rootfs/templates/kops/default.yaml
* Add `additionalPolicies` with `sts:AssumeRole` to `kops` template
* Allow `kops` clusters created from the template to assume IAM roles
* Use with `kube2iam`
=> Add `additionalPolicies` to `kops` template

Dockerfile, rootfs/etc/profile.d/prompt.sh, rootfs/templates/kops/default.yaml, rootfs/templates/scaffolding/Makefile, rootfs/usr/local/bin/new-project, rootfs/usr/local/include/helpers
* Change ENV var name from `CLUSTER_NAME` to `KOPS_CLUSTER_NAME`
* To standardize on the ENV var name for `kops` clusters
*  `KOPS_CLUSTER_NAME` is used in the `kops` sources and official docs
* https://github.com/kubernetes/kops/blob/05378903178e66cbb36a934cb9c0ab02214568a4/cmd/kops/root.go#L131
=> Change ENV var name from `CLUSTER_NAME` to `KOPS_CLUSTER_NAME`

rootfs/templates/wrapper
* Remove bash4 syntax (e.g. `declare -g` and `${k^^}`)
* Fix mounting of `$HOME` for linux systems (regression)
* Requiring `bash4` increases barrier of adoption without adding significant benefits. Minor drawback is we require `tr` instead.
* https://github.com/cloudposse/geodesic/issues/112
=> Backwards Compatibility for Bash v3

rootfs/etc/profile.d/prompt.sh
* Use `BANNER` instead of `KOPS_CLUSTER_NAME` for prompt
* When provisioning an architecture without `kops`, `KOPS_CLUSTER_NAME` does not exist, and `geodesic` shows the default prompt not related to the current solution
* `geodesic` is designed to work with many different architectures, not only `kops`
=> Use `BANNER` instead of `KOPS_CLUSTER_NAME` for prompt

conf/kops/helmfile.yaml
* `0.1.2` -> `0.1.5`
* `0.1.2` contains a bug that prevents certs from getting generated
=> Upgrade kube-lego

Dockerfile
* Remove extraneous `\`
* Silent error
=> Fix typo affecting use of net.ipv6.conf.all.disable_ipv6=0

README.md
* Link to new slack site: <https://slack.cloudposse.com>
* Promote community support
=> Promote Slack Team

rootfs/conf/kops/helmfile.yaml
* Add `datadog.apmEnabled` value to datadog release in the kops helmfile
* Allows the datadog daemonset to be deployed to APM enabled
=> add datadog apm enabled value to kops helmfile

rootfs/templates/wrapper
* Look for a default env file and pass it to docker if found
* Fixes #149
=> rootfs/templates/wrapper: add GEODESIC_DEFAULT_ENV_FILE

rootfs/conf/kops/helmfile.yaml
* Bump DataDog chart version
* Add `daemonset.useHostPort` value
* Add `daemonset.updateStrategy` value
* The latest chart version supports newer versions of the DataDog agent
* `daemonset.useHostPort` set to `true` allows trace agents from pods on the same node to report using the `hostIP`
* `daemonset.updateStrategy` can be set to `RollingUpdate` to relaunch DataDog agent pods when the chart is installed or updated
=> add DataDog useHostPort and updateStrategy values to master helmfile

rootfs/conf/kops/helmfile.yaml
* add ingress annotation for chartmuseum in master helmfile
* change `chart` label for `charts-api` release to `chartmuseum`
* The ingress annotation is needed to provision external DNS for chartmuseum.
* The `chart` label for `charts-api` and `charts` releases should be the same
=> add ingress annotation for chartmuseum in master helmfile

Dockerfile
* Update Kubernetes and Kops versions from 1.8.7 to 1.9.1
* Update kops base image
* Significantly out of date
* Built Geodesic locally using my changes then upgraded a cluster from 1.8.7 to 1.9.1
=> Update Kubernetes and Kops versions to 1.9.1

rootfs/conf/kops/helmfile.yaml
Previously this used an old spec that caused newer installations of the this chart to fail. `storageSpec` has since been updated to just `storage`
See:
https://github.com/coreos/prometheus-operator/issues/860#issuecomment-370999129
Modified this file and deployed the kube-prometheus chart to a cluster.
=> Fixing outdated syntax for Prometheus PVCs

rootfs/conf/kops/helmfile.yaml
* Force iptables DNAT rule to reroute `169.254.169.254` to the `kiam` agent metadata proxy
* Kiam stopped working; not entirely sure why
* Seems to have happened after upgrading to k8s 1.9.1
> This is the process that would typically be deployed as a DaemonSet to ensure that Pods have no access to the AWS Metadata API. Instead, the agent runs an HTTP proxy which intercepts credentials requests and passes on anything else. An DNAT iptables rule is required to intercept the traffic. The agent is capable of adding and removing the required rule for you through use of the --iptables flag. This is the name of the interface where pod traffic originates and it is different for the various CNI implementations. The flag also supports the ! prefix for inverted matches should you need to match all …
=> kiam agents should use iptables to intercept traffic

rootfs/conf/kops/helmfile.d/0510.fluentd.yaml
* Change version of fluentd image
* New version fix `json` issue
- <https://github.com/cloudposse/fluentd-datadog-logs/releases/tag/0.1.1>
=> Fix fluentd json issue

rootfs/conf/kops/helmfile.d/0510.fluentd.yaml
* Switch `fluentd` chart to `fluentd-kubernetes`
* Use generic chart
* It's going to be a while before [official chart PR](https://github.com/kubernetes/charts/pull/5357) gets approved
=> Use cloudposse fluentd chart

rootfs/conf/kops/helmfile.yaml
* Backport fluentd fixes
* We reverted all `helmfile.d` stuff which reverted the `fluentd` fixes
* <https://github.com/cloudposse/geodesic/pull/178>
* <https://github.com/cloudposse/geodesic/pull/177>
* <https://github.com/cloudposse/geodesic/pull/176>
=> Backport fluentd fixes

Dockerfile
* Add `/packages/install` to image
* To make it easier for inheritors to upgrade select packages
* It's referenced in our [documentation](https://docs.cloudposse.com/geodesic/kops/upgrade-cluster/)
e.g. Add this to a `Dockerfile`
```
RUN make -C /packages/install kubectl KUBECTL_VERSION=1.10.0
```
```
❌   (none) ~ ➤  make -C /packages/install kubectl KUBECTL_VERSION=1.10.0
make: Entering directory '/packages/install'
curl --fail -sSL -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.10.0/bin/linux/amd64/kubectl
chmod +x /usr/local/bin/kubectl
make: Leaving directory '/packages/install'
```
=> Copy installer

rootfs/conf/kops/helmfile.yaml
Use env var CHARTMUSEUM_API_HOSTNAME for the chartmuseum API release instead of `api.{{ env "CHARTMUSEUM_HOSTNAME" }}`
Allow other host naming conventions.
In my case, I want to use `api-charts.us-west-2.staging.example.com` as the hostname so that a `*.us-west-2.staging.example.com` certificate applies.
1. Define `CHARTMUSEUM_API_HOSTNAME` with `chamber` (e.g. `api.charts.us-west-2.staging.cloudposse.org`)
=> use CHARTMUSEUM_API_HOSTNAME

Makefile
* Add -E option to sudo
* All env variables doesn't import automatically 
- <https://github.com/cloudposse/geodesic/issues/196>
- <https://github.com/cloudposse/root.cloudposse.co/issues/6>
=> Preserve Environment When Sudo'ing

Dockerfile
* Use correct path for autocompletion scripts
* Completers are located in another directory
- <https://github.com/cloudposse/geodesic/issues/144>
=> Fix path for AWS Autocompletion

rootfs/etc/profile.d/prompt.sh
* Restore ✅
* The ✔is too discreet and doesn't match ❌
=> Restore white checkmark in unicode prompt

Makefile, rootfs/etc/syslog-ng/syslog-ng.conf
* Bump `@version` in `syslog-ng.conf`
* In `alpine:3.8` version of `syslog-ng` was bumped and now it throws WARNING
- https://github.com/cloudposse/geodesic/issues/206
=> Update syslog ng conf

rootfs/etc/profile.d/syslog-ng.sh
Check if syslog-ng is already running
#211
=> syslog-ng: check existing instance

rootfs/etc/profile.d/prompt.sh
* Add new *default* prompt style that uses single byte width characters
* The multi-byte unicode characters causes problems on terminals with line wrapping and broken command history
* Better portability
* Wide-Unicode support requires "Use Unicode Version 9 widths" feature flag enabled in iTerm2
* https://github.com/cloudposse/geodesic/issues/212
=> Add color prompt with single byte width characters

rootfs/etc/profile.d/syslog-ng.sh
* Remove `-x` argument
* Unsupported on the `alpine` version of `pidof` command
* https://github.com/cloudposse/geodesic/pull/215
* https://github.com/cloudposse/geodesic/issues/217
=> Remove unsupported `-x` argument for `pidof`

rootfs/etc/profile.d/aws-vault.sh
* Check if aws-vault server is already running before attempting to start
* Can only run once since it attempts to bind to `169.254.169.254`
* #195
=> aws-vault - fix shell concurrency

rootfs/etc/profile.d/aws.sh
* Symlink `/conf/.aws` to `/localhost/.aws`
* In geodesic `HOME=/conf` and `/localhost/.aws` is the canonical aws configuration
* `aws configure` does not respect `AWS_DATA_PATH`
* https://github.com/cloudposse/geodesic/issues/225
=> Fix AWS Configure Support

Dockerfile
* Deprecate `VOLUME` definition for `CACHE_PATH`
* It shadows `/localhost` which already is mounted
* If a volume is not explicitly mounted with `--volume` to match the `CACHE_PATH`, then docker creates a temporary ephemeral volume
* We want data to persist in this path
=> Deprecate VOLUME for CACHE_PATH

rootfs/usr/bin/s3fs
check if fs is already mounted before calling `mount -a`
#187
=> s3fs - check if fs is already mounted

rootfs/etc/profile.d/iterm.sh
* Preserve exit status code of last command when exiting
* Necessary for proper testing
=> Preserve Exit Status Code on Exit

rootfs/etc/profile.d/aws-vault.sh
* use `mkdir -p` to create parent dirs
* If `/localhost` is not mounted, this fails
* running under CI/CD `/localhost` may not be mounted
=> Create aws-vault parent directories

rootfs/etc/profile.d/aws-vault.sh
* add `connect-timeout` param
* if metadata api is unavailable then we should timeout quickly
* https://github.com/cloudposse/geodesic/issues/236
=> Add connect timeout

Dockerfile, rootfs/templates/wrapper
* Add `--with-docker` argument 
* Access docker daemon from inside of geodesic
* Run tasks that need docker (E.g. from `build-harness`)
* Only works on Linux because sockets cannot be bind mounted into VMs
=> Add --with-docker arg

Dockerfile
* Install `oath-toolkit`
* Easy build one-time password authentication systems (including for AWS with MFA)
* Required for Terraform CI/CD
```
Step 65/74 : RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories     && apk add --no-cache oath-toolkit-oathtool
---> Running in b83396d5fa96
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
(1/5) Installing perl (5.26.2-r1)
(2/5) Installing cvs (1.11.23-r0)
(3/5) Installing diffutils (3.6-r1)
(4/5) Installing oath-toolkit-liboath (2.6.2-r0)
(5/5) Installing oath-toolkit-oathtool (2.6.2-r0)
Executing busybox-1.28.4-r0.trigger
OK: …
```
=> Install `oath-toolkit`

Dockerfile
* Install `bats-core`
* Automated tests
* https://github.com/cloudposse/geodesic/issues/259
```
Step 63/74 : RUN curl --fail -sSL -O https://github.com/bats-core/bats-core/archive/v${BATS_CORE_VERSION}.tar.gz 
&&  tar -zxf v${BATS_CORE_VERSION}.tar.gz 
&&  mv bats-core-${BATS_CORE_VERSION} /usr/local/ 
&&  /usr/local/bats-core-${BATS_CORE_VERSION}/install.sh /usr/local 
&&  rm -rf bats-core-${BATS_CORE_VERSION}.tar.gz
---> Running in 564fc45d39b7
Installed Bats to /usr/local/bin/bats
```
=> Install `bats-core`

Dockerfile
added helm-s3 plugin that allows to have private Helm chart repositories hosted on Amazon S3
closes #269
=> [helm] add helm-s3 plugin

Dockerfile, requirements.txt
* Copy Google Cloud SDK from official Docker image using multi-stage build
* Upgrade to latest release
* Fix `gcloud` bash completion
* Support automatic dependency updates by dependabot
* Faster build times
=> [gke] Use Google Cloud SDK Image

Dockerfile
* Add `gettext`
* To include `envsubst`
* Needed to use `geodesic` as Docker image in Codefresh pipelines
=> Add gettext

Dockerfile
* Upgrade helm-diff
* To support `--set-file` syntax which was recently added to `helm`
* Breaks our CI without it
=> [helm-diff] upgrade to 2.11.0+2

rootfs/templates/kops/default.yaml
* Add configurable `idleTimeoutSeconds` for k8s API load balancer
* Some `helm` deployments take more than 5 minutes (default apiserver ELB timeout)
* https://github.com/kubernetes/kops/pull/1886
=> Add configurable `idleTimeoutSeconds` for k8s API load balancer

packages.txt, rootfs/etc/profile.d/direnv.sh
* Add `direnv` support which automatically loads *allowed* `.envrc` files
* Simplify env management in a standardized way that's commonly used by the community
* Automatically export envs from chamber
Sample `conf/kops/.envrc`:
```
eval "$(chamber exec kops -- sh -c "export -p")"
```
* https://direnv.net/
=> Add direnv support

requirements.txt, rootfs/usr/local/bin/aws-config-setup
* Add a script to easily configure `.aws/config` profiles for the given account following cloudposse conventions
* Call `aws-vault add` to prompt for access credentials
* Add crudini to easily manipulate ini files (because `aws configure` sucks)
* Simplify the coldstart problem for new users when using a preconfigured shell
=> Add script to easily setup `~/.aws/config` with `aws-vault`

rootfs/templates/wrapper
* Remove default value for `DOCKER_DNS`
* In corporate environments, DNS is often tightly regulated
* No longer needed to address the [original problem](https://github.com/moby/moby/issues/24344)
* Closes #320
=> Remove default for DOCKER_DNS

rootfs/etc/profile.d/aws.sh, rootfs/etc/profile.d/terraform.sh
* Fix autocomplete for `aws` and `terraform` 
* They broke when we moved to install alpine packages
* Fixes #300
=> Fix autocomplete for terraform and aws

Dockerfile, rootfs/templates/scaffolding/Dockerfile
Update default KOPS_BASE_IMAGE for 1.10
We want to bump Kops to latest 1.10.X release for CVE-2018-1002105. This
commit ensures the default Kops AMI is 1.10. See [1]
[1] https://github.com/kubernetes/kops/blob/master/channels/stable#L22
This can be merged once https://github.com/cloudposse/geodesic/pull/326 has shipped and can be rebased to only include the KOPS_BASE_IMAGE changes.
=> Update Kops base image to 1.10

rootfs/usr/local/bin/aws-config-setup
* Use `OrganizationAccountAccessRole` when assuming into other accounts
* Root account follows different convention from subaccount
=> Use OrganizationAccountAccessRole to go between accounts

packages.txt
* Add `tfenv` package
* Easily transform environment variables for use with terraform
=> [tfenv] add package

rootfs/etc/profile.d/ssh-agent.sh
* Allow the path the default SSH key to be overridden (or disabled)
* When working with multiple organizations, keys other than `id_rsa` might be used
* It's nice to disable the password prompt if not using agent
=> support SSH_KEY env

rootfs/templates/kops/default.yaml
* [kops/template] Add `KOPS_NETWORK_CIDR` ENV var
* When using custom `KOPS_PRIVATE_SUBNETS` and `KOPS_UTILITY_SUBNETS`, need to update `networkCIDR` as well. Otherwise the error is thrown:
```
error: error creating cluster: Spec.Subnets[0].CIDR: Invalid value: "10.90.128.0/25": Subnet had a CIDR "10.90.128.0/25" that was not a subnet of the NetworkCIDR "172.20.0.0/16"
```
=> [kops/template] Add `KOPS_NETWORK_CIDR` ENV var

.editorconfig, Dockerfile, rootfs/etc/profile.d/prompt.sh
* Add support for the fancy `PS1` prompt for kubernetes
* Improved UX - show current kubernetes context/namespace
* Useful when operating with multiple kubernetes clusters
* closes #290
=> [kube-ps1] add fancy kube PS1 prompt support

rootfs/usr/local/bin/aws-config-setup
* Use correct spelling of `ACCOUNT`
* Typo
=> [aws-config-setup] Fix typo

rootfs/templates/kops/default.yaml
* [kops/template] Update `aws-iam-authenticator` settings
* Kubernetes `1.10` and newer has `aws-iam-authenticator` installed by default, no need to add scripts to install it from S3
* https://github.com/kubernetes/kops/blob/master/docs/authentication.md
* https://github.com/kubernetes-sigs/aws-iam-authenticator
* https://aws.amazon.com/blogs/opensource/deploying-heptio-authenticator-kops/
* https://ifritltd.com/2018/09/09/kubernetes-authentication-with-aws-iam/
* `IAM authenticator config map` (to map IAM principals to k8s users) still needs to be created and applied in TF
=> [kops/template] Update `aws-iam-authenticator`

Dockerfile, rootfs/etc/profile.d/geodesic.kube-ps1.sh
* Turn prompt on when `KUBECONFIG` found (`kubeon`)
* Turn prompt off when `KUBE_PS1_KUBECONFIG_CACHE` is no longer found (`kubeoff`)
* `kube-ps1` does not properly handle kubeconfigs that go missing (it keeps displaying the last known context)
* Improve the UX by not expecting users to know they should run `kubeon` and `kubeoff`
=> [kube-ps1] Automatically enable/disable prompt

Dockerfile, rootfs/etc/profile.d/terraform.sh
Move `TF_PLUGIN_CACHE_DIR` to runtime var
This should be a non breaking change as it defaults to 
`/localhost/.terraform/plugins` but allows us to override if necessary
e.g. The atlantis user does not have write access to /localhost
=> Set TF_PLUGIN_CACHE_DIR at runtime

rootfs/etc/init.d/atlantis.sh
* Turn on `-auto-approve` in `atlantis`
* Atlantis cannot prompt the user for interactive approval (That's what Pull Request "approvals" are for..)
=> [atlantis] Turn on auto approve

rootfs/etc/direnv/rc.d/atlantis, rootfs/etc/direnv/rc.d/terraform
* Add `use atlantis` direnv stdlib function
* This adds `atlantis` specific run-time functionality that we can use with `tfenv` to support [planfiles](https://www.terraform.io/docs/commands/plan.html#out-path)
Run `terraform plan` and `terraform apply` and automatically use planfiles without needing to pass any arguments
=> [direnv] Add atlantis support for planfile

Dockerfile
Add helm-git plugin instead of helm-github
We would like a a way to release from non-packages helm repositories, 
directly from git, with a ref and path specification. See [1]
`helm-git` supports `git` scheme making it compatible with `helmfile`
This closes [2]
[1] https://github.com/roboll/helmfile/issues/435
[2] https://github.com/cloudposse/geodesic/issues/355
=> Add helm-git plugin instead of helm-github

rootfs/etc/init.d/atlantis.sh
This PR fixes the SSH agent for Atlantis by running it under the "ATLANTIS_USER" account.
=> Fixing SSH agent for Atlantis

rootfs/usr/local/bin/kopsctl
* Add commands to easily rotate a kops cluster's ssh keys
* Add command to easily connect to a kops cluster
* Add command to see a kops plan
* This are routine operations that are complicated to express in documentation
=> [kopsctl] add commands to facilitate management of cluster

Dockerfile, rootfs/etc/profile.d/_colors.sh, rootfs/etc/profile.d/aws-vault.sh, rootfs/templates/kops/kubecfg.yaml, rootfs/usr/local/bin/build-kubecfg, rootfs/usr/local/bin/kopsctl
This commit adds a command `kopsctl login` to build a kubecfg that optionally can use
aws-iam-authenticator, given we have the `KOPS_AWS_IAM_AUTHENTICATOR_ENABLED` set to true
We want to enable RBAC using aws-iam-authenticator to auth users against the Kops cluster via IAM roles.
Note that we have to fetch the CA data using `openssl s_client` as we don’t have a kubecfg to pull it from yet and we don't want to have to access the Kops state store S3 bucket where this information is stored.
Note this is a non breaking change and while we _can_ use the templated `kubecfg`, as admin operators, we can still run `kops export kubectl`.
`kopsctl login` should be run after assuming an AWS role within Geodesic.
There will be further PRs to create specific IAM roles for `KubernetesAdmin` and …
=> Better support for aws-iam-authenticator

rootfs/etc/profile.d/aws-vault.sh
Default to AWS_DEFAULT_PROFILE for IAM assume-role
If AWS_IAM_ROLE_INTERACTIVE is not set, we default to previous behaviour
of using AWS_DEFAULT_PROFILE and not prompting via selector. Rather
than removing our (CloudPosse) use of AWS_DEFAULT_PROFILE from the stage
Dockerfiles, check for the presence of AWS_IAM_ROLE_INTERACTIVE var. AWS_DEFAULT_PROFILE is used in other places, so we don’t want to remove it. 
`assume-role` therefore has the following precedence:
`assume-role $role` - assumes $role
`assume-role`           - with AWS_IAM_ROLE_INTERACTIVE set will prompt with a  role selector 
`assume-role`           - assumes $AWS_DEFAULT_PROFILE
=> Default to AWS_DEFAULT_PROFILE for IAM assume-role

rootfs/etc/profile.d/prompt.sh
- Adds delimiters around terminal escape sequences, so `readline` has accurate cursor position.
Tested for `PROMPT_STYLE=plain` on `xterm`.
- Removes an extraneous double space after the final `=>` arrow in the prompt.
bash->readline was incorrectly wrapping command line text while typing interactively and while browsing shell history.
=> [prompt]: add hints so readline correctly tracks cursor

Dockerfile, packages.txt, requirements.txt, rootfs/etc/profile.d/aws-okta.sh, rootfs/etc/profile.d/aws-vault.sh
* `$0` does not emit a helpful 
* Add `sudo` so the `--server` mode flag works without the `aws-vault server&` hack
* Update `aws-cli`
* Normalize `AWS_VAULT_SERVER_ENABLED` env
* Add support for `AWS_VAULT_SESSION_TTL`
* `aws-vault` appears to be having some trouble with `--server` mode; rather than rip it out entirely, we'll disable it by default for now
* https://github.com/99designs/aws-vault/issues/339
* https://github.com/99designs/aws-vault/issues/338
* https://github.com/99designs/aws-vault/issues/335
=> Rename aws-vault server enabled flag

rootfs/etc/profile.d/aws-vault.sh
When the System Time and the Hardware Clock disagree, sync them.
Specifically, if one clock is behind the other by more than 10 seconds, set the lagging clock to the leading clock, because it is almost always the case that the slow clock is wrong.
AWS credentials have very limited lifetime which is enforced by tying their validity to real-world time. If the clock is wrong, then authentication will fail, so accurate real-world time is essential.
=> Intelligently sync the clocks when they are out of sync

rootfs/etc/profile.d/inputrc.sh
adds a small profile.d script that copies the user's homedir `.inputrc` if it exists at geodesic container startup.
Readline keybindings are typically stored in a user's `~/.intputrc`.
This script allows those keybindings to smoothly flow into the geodesic env.
=> profile.d: copy and use inputrc from localhost

Dockerfile, rootfs/etc/profile.d/fzf.sh
* Disable bash completion for `fzf` if non-interactive terminal
* The upstream bash completion script has a bug where it doesn't handle this use-case
=> [fzf] Fix for non-interactive mode

rootfs/etc/profile.d/aws-vault.sh
* Support disabling the time-drift correction
* It's slow and not necessary when running docker natively
=> [aws-vault] add feature flag for time drift correction

rootfs/etc/profile.d/aws-vault.sh
change the starting point for role names (when assuming a role) from $NAMESPACE to $NAMESPACE-$STAGE
Too many roles under just $NAMESPACE, plus roles should be scoped to stages anyway
=> Include $STAGE in role prefix

rootfs/templates/kops/default.yaml
Mitigate [cve-2019-5736](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-5736) by making runc immutable
When running a process as root (UID 0) inside a container, that process can exploit a bug in `runc` to gain root privileges on the host running the container. This then allows them unlimited access to the server as well as any other containers on that server. The implemented change mitigates this risk.
This mitigation was described [here](https://seclists.org/oss-sec/2019/q1/134) and affirmed [here](https://twitter.com/_staaldraad/status/1095354945073754112) and [here](https://github.com/kubernetes/kops/blob/master/docs/advisories/cve_2019_5736.md#cve-2019-5736---runc-container-breakout) with the caveat that privileged pods (that are effectively root anyway) and pods that have …
=> [aws/kops] Mitigate cve-2019-5736 by making runc immutable

rootfs/etc/profile.d/aws-vault.sh
If the login shell detects that the `aws-vault` credential server is running, immediately assume that role.
The `aws-vault` credential server is not just convenient, it is essential for enabling long-running tasks (such as `kops rolling-update cluster`) to complete without credentials expiring. However, `aws-vault` has a limitation that `aws-vault exec` will not use an existing credential server, forcing the user to use non-server mode, where expired credentials will not be renewed.  This change works around that limitation by detecting a running credential server and acting as if `assume-role` had been called to assume the role being served by the credential server.
=> [aws-vault] Resume current role if aws-vault server is running

rootfs/conf/.inputrc, rootfs/etc/profile.d/inputrc.sh
Removes the script `profile.d/inputrc.sh`.
In its place, we add symlink to the default geodesic user's home directory:
`/conf/.inputrc -> /localhost/.inputrc` 
This seems simpler than a script that tests for and reads the file from `/localhost`.
Why add a script when a simple symlink suffices?
=> [.inputrc] Use symlink in /conf instead of another script

docs/design.md, rootfs/etc/direnv/rc.d/terraform
* `TF_BUCKET_PREFIX_FORMAT` selects the format to use for setting the TF
remote state bucket prefix/key: the original `$(basename $(pwd))`
leaf-only format, or the new full path format.
Old format uses leaf directory only, which could lead to unexpected
behaviour if you used subdirectories for structuring:
/conf/us-east-1/vpc    -> s3://<bucket>/vpc
/conf/eu-central-2/vpc -> s3://<bucket>/vpc
New format uses full path:
/conf/us-east-1/vpc    -> s3://<bucket>/us-east-1/vpc
/conf/eu-central-2/vpc -> s3://<bucket>/eu-central-2/vpc
* closes #401
=> [direnv] use new TF bucket prefix method

rootfs/etc/profile.d/aws-vault.sh, rootfs/templates/kops/default.yaml
- Optionally install [Teleport](https://gravitational.com/teleport/) node agent on all instances
- Give all instances permission to view AWS tags (permission `ec2:DescribeTags`)
- Restore permissions to allow Masters to autoscale when `KOPS_CLUSTER_AUTOSCALER_ENABLED` is `true`
- Teleport node agents must be installed on instances, so it must be done by `kops`. 
- Permission to read tags in preparation of better automatic labeling.
- Autoscale permissions were previously not enabled due to a typo.
=> [kops template] Optionally install Teleport on all Instances

packages.txt
Add tools to help with investigating Kubernetes RBAC:
- [rakkess](https://github.com/corneliusweig/rakkess) kubectl plugin to show an access matrix for all available resources
- [rbac-lookup](https://github.com/reactiveops/rbac-lookup) Find roles and cluster roles attached to any user, service account, or group name in a kubernetes cluster 
Support implementing meaningful access control policies in kubernetes using RBAC
=> [packages] Add tools rakkess and rbac-lookup

rootfs/templates/kops/default.yaml
Add additional script to extract the Kubernetes role of an instance from AWS tags and use it to create a Teleport label for each instance
Better descriptions in teleport lists
=> [kops template] Add kubernetes role label to Teleport agent

rootfs/etc/direnv/rc.d/envrc
* Add `use envrc` helper
* Load all `.envrc` files in a directory (or based on a custom wildcard)
Add `use envrc` to your `.envrc` files to automatically include all envrcs
=> Add envrc stdlib function

rootfs/etc/profile.d/banner.sh, rootfs/templates/wrapper
* Update wrapper script to use the `docker ps --filter` option rather than pipe/grep pattern
- #415 points out that `pipefail` is unreliable, so lets just eliminate it as a factor in this case
=> [rootfs/templates/wrapper] Use docker native filtering with ps

rootfs/etc/direnv/rc.d/envrc
Fix to `use envrc` addition to `direnv` to avoid an infinite loop condition.
Apparently, direnv executes a separate shell with `nullglob` and `failglob` both off, causing the raw glob to be passed to a future `eval`, causing a loop.
=> [direnv] Avoid infinite loop

rootfs/etc/profile.d/terraform.sh, rootfs/templates/wrapper
Eliminate cases where turning on the `bash` shell's `nullglob` option lingers past its intended scope.
The `bash` shell setting `shopt -s nullglob` changes the way "globs" are handled when they do not match any files. It had been being set in the prompt hook, meaning it was set for every command running in Geodesic. This caused weird behavior, like this:
```
⨠ ls
a-file	b-file
⨠ ls a*
a-file
⨠ ls b*
b-file
⨠ ls c*
a-file	b-file
```
It could likewise cause other commands and shell scripts to fail or behave unexpectedly. 
[Why is nullglob not default?](https://unix.stackexchange.com/a/204944)
[Test whether a glob has any matches in bash](https://stackoverflow.com/a/34195247)
=> Eliminate non-local effects of shopt -s nullglob

rootfs/etc/direnv/rc.d/envrc
Following up on #418, match function execution with description, specifically: allow multiple arguments to `use_envrc`
Convenience of multiple arguments vs multiple single-argument calls. 
https://github.com/direnv/direnv/issues/480
#418
=> [direnv]  Support multiple arguments to `use_envrc`

rootfs/etc/syslog-ng/syslog-ng.conf
Update syslog-ng configuration to 3.19
Required to get rid of the warning messages shown below since upgrading to `syslog-ng` version 3.19 in our [release 0.80.0](https://github.com/cloudposse/geodesic/releases/tag/0.80.0)
```
[timestamp] WARNING: Configuration file format is too old, syslog-ng is running in compatibility mode. Please update it to use the syslog-ng 3.19 format at your time of convenience. To upgrade the configuration, please review the warnings about incompatible changes printed by syslog-ng, and once completed change the @version header at the top of the configuration file.;
[timestamp] WARNING: With use-dns(no), dns-cache() will be forced to 'no' too!;
```
=> [syslog-ng] Update syslog-ng configuration to 3.19

rootfs/templates/kops/default.yaml
Set the correct permissions on the teleport binary installed on the node instances.
Incorrect permissions prohibited non-root users from accomplishing authorized tasks such as `scp`.
=> [teleport] Fix permissions on teleport daemon

Dockerfile, packages.txt, rootfs/conf/.emacs, rootfs/etc/profile.d/_colors.sh, rootfs/etc/profile.d/_geodesic-config.sh, rootfs/etc/profile.d/_geodesic-dotfiles.sh, rootfs/etc/profile.d/_preferences.sh, rootfs/etc/profile.d/aliases.sh, rootfs/etc/profile.d/aws-vault.sh, rootfs/etc/profile.d/direnv.sh, rootfs/etc/profile.d/fzf.sh, rootfs/etc/profile.d/geodesic.kube-ps1.sh, rootfs/etc/profile.d/prompt.sh, rootfs/etc/profile.d/stty.sh, rootfs/etc/profile.d/tfenv.sh, rootfs/etc/profile.d/Ω_finalize.sh, rootfs/etc/profile.d/Ω_overrides.sh, rootfs/templates/wrapper
In addition to some small cleanups and additions, provide a capability for users to customize Geodesic at runtime.
Because people vary, their computers vary, what they are trying to accomplish varies, and while we love to standardize, we know there is no such things as one best way for everyone.
Users can place bash shell scripts on their host computer, to be read either at the start of `bash` profile script processing or at the end of it. Users can also choose whether to have a single `bash` history file for all containers or to have separate history files.
All configuration files are stored under `GEODESIC_DOT_DIR`, which defaults to `/localhost/.geodesic`. At this time, `/localhost` is mapped to the host `$HOME` directory and this cannot be configured yet, so all configuration files …
=> Enable run-time customization

rootfs/templates/kops/default.yaml
Install iptable entry required by `kiam`. 
WARNING: With this `kops` Cluster configuration, pods (on nodes) will have **_no_** access to the AWS metadata server unless `kiam` is installed. To ensure continued access to the metadata server in the absence of `kiam`, set the environment variable `KIAM_INSTALLED` to `"false"` before running `make kops/build-manifest`.
Support rolling update of `kiam` agents required by https://github.com/cloudposse/helmfiles/pull/109 and included in  helmfiles release 0.26.0 in light of https://github.com/uswitch/kiam/issues/202
=> [templates/kops] Install iptable entry required by kiam

rootfs/etc/profile.d/_preferences.sh
Due to a programming error, the `bash` history file was not being properly found and loaded. This fixes that so that the history file is found as described in #422 and loaded.
Fix bug.
=> [history] Fix bash history file initialization

.travis.yml, Makefile, packages.txt, rootfs/etc/profile.d/aws-vault.sh, rootfs/etc/profile.d/fzf.sh, rootfs/etc/profile.d/prompt.sh
- Add option to set `GEODISIC_PROMPT_GLYPHS` to set (or remove) glyphs at end of command line prompt
- Set `fzf` to use plain ASCII when `PROMPT_STYLE` is set to `plain`.
Partly address issues such as #417
=> [prompt], [fzf] Slightly better support for Unicode-challenged terminals

Dockerfile, Makefile, packages.txt, rootfs/etc/profile.d/_geodesic-config.sh, rootfs/etc/profile.d/_preferences.sh, rootfs/etc/profile.d/aws-vault.sh, rootfs/etc/profile.d/fzf.sh, rootfs/usr/local/bin/aws-config-setup
- Fix long delay at startup when opening TCP SYN packet is not rejected
- Fix use of `aws-vault` server when Docker is running on AWS and has a default route to the instance meta-data server
- Create `GEODESIC_CONFIG_HOME` directory if it does not exist
- Remove `sudo` from install recipe
- Add back missing bash completion script for `fzf`
- Do not create symbolic link for `fzf` bash completion if the file does not exist
- Fix trace message for config file search
- Remove GEODESIC_PATH (dead code)
These are bugs that typically only show up on first or early use.
=> [aws-vault] Fix startup hang and other misc problems

rootfs/etc/profile.d/_preferences.sh, rootfs/etc/profile.d/aws-vault.sh
- Better detection of when aws-vault server needs to be explicitly started
- Proper creation of `HISTFILE` when no existing file can be found
- Anti-virus programs like ESET NOD32 Internet Protection can confuse `aws-vault` into thinking a meta-data server is already running.
- Previously if no default was set and no `history` file was found, history was saved in the ephemeral file system, causing it to be lost on exit.
=> [aws-vault] Better detection of when aws-vault server needs to be explicitly started

rootfs/etc/direnv/rc.d/terraform, rootfs/templates/kops/default.yaml, rootfs/usr/local/bin/aws-config-setup, rootfs/usr/local/bin/build-kops-manifest, rootfs/usr/local/bin/build-kubecfg
- [build-kops-manifest] Support using remote templates for kops manifest 
- [build-kubecfg] Support using remote templates for kubecfg 
Move templates to cloudposse/reference-architectures. (Templates left in Geodesic for backwards compatibility and transitional support.)
=> [build-kops-manifest] Support using remote templates for kops manifest and kubecfg

Dockerfile
- Update packages alpine version from 3.8 to 3.9
- bump cloudposse/packages from 0.81.0 to 0.82.0. Closes #433 
- bump google/cloud-sdk from 239.0.0-alpine to 241.0.0-alpine. Closes #437 
- Maintain consistency between package and Dockerfile Alpine versions
- Track latest google/cloud-sdk
=> [Dockerfile] Bump google cloud-sdk to 241, fix packages Alpine version

Dockerfile, rootfs/etc/profile.d/iterm.sh, rootfs/etc/profile.d/stty.sh
* Fix error `stty: 'standard input': Not a tty` caused by calling `stty` when no tty attached
* Fix error `tput: No value for $TERM and no -T specified`
* Running `geodesic` based containers in CI/CD contexts (e.g. codefresh) often means there won't be a tty attached
>  The terminal type "dumb" may be needed when an application program can't figure out what type of terminal you are using.
=> Fix stty error for non-interactive sessions

rootfs/etc/direnv/codefresh
* Add a script to initialize codefresh environment from direnv (`cf_export`)
* We use `direnv` consistent across multiple platforms
* This allows us to use our `use ...` stdlib helpers in codefresh to facilitate terraform usage
=> [direnv/codefresh] add initializer

geodesic_apkindex.md5, packages.txt, rootfs/etc/profile.d/aws-vault.sh, rootfs/etc/profile.d/prompt.sh
Enhance shell prompt to indicate the presence of `kops` secrets in your shell environment
```
⧉  data 
√ . (cpco-prod-admin) kops ⨠ make kops/shell 
chamber exec kops -- bash -l
* Assumed role arn:aws:iam::00000000000000:role/OrganizationAccountAccessRole
⧉  data +
√ ⋮ (cpco-prod-admin) kops ⨠ kops export kubecfg 
kops has set your kubectl context to us-west-2.prod.cpco.io
⧉  data (us-west-2.prod.cpco.io:default)+
√ ⋮ (cpco-prod-admin) kops ⨠ exit
logout
⧉  data (us-west-2.prod.cpco.io:default)
√ . (cpcp-prod-admin) kops ⨠ 
```
Provide awareness of whether or not secrets are available to commands you are running
Use in  conjunction with environment altering commands:
```
function chdo() {
source <(chamber export -f dotenv "$@" | sed "s/^/export /" | perl -pe s/\\\\n/\\n/g)
}
function …
```
=> [prompt] Enhance shell prompt to indicate presence of chamber secrets

rootfs/etc/profile.d/aws-vault.sh, rootfs/etc/profile.d/tsh-login.sh, rootfs/etc/profile.d/tsh.sh
[tsh-login] Distinguish login proxy name from local cluster name
There are 2 relevant proxy names for trusting clusters and they are used differently
=> [tsh] Use official tsh environment variables for port, proxy, & ssh login

Makefile, rootfs/templates/wrapper
- Fix `make install`
- Pass `DOCKER_IMAGE` into running container via `wrapper` script
- `make install` was broken by #447
- `DOCKER_IMAGE` is use by "preferences" mechanisms to locate image-specific preferences.
=> [Makefile]  Fix broken "make install", [preferences] Fix search for preferences in base image

Dockerfile, README.md, README.yaml, docs/kops.md, rootfs/templates/README.md
- Update `kops` documentation. Supersedes and closes #339 
- Update Dockerfile:
- Upgrade Kubernetes version, AWS instance types:
- KUBERNETES_VERSION 1.10.11 -> 1.11.9
- KOPS_BASE_IMAGE `kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17` -> `kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17`
- BASTION_MACHINE_TYPE t2.medium -> t3.small
- MASTER_MACHINE_TYPE t2.medium -> t3.medium
- NODE_MACHINE_TYPE t2.medium -> t3.medium
- Remove `ENV` variables that should not have defaults:
- KOPS_STATE_STORE
- KOPS_STATE_STORE_REGION
- KOPS_FEATURE_FLAGS
- KOPS_PRIVATE_SUBNETS
- KOPS_UTILITY_SUBNETS
- KOPS_AVAILABILITY_ZONES
Bring in line with current Reference Architecture and recommendations.
=> [kops] Update documentation and Dockerfile

rootfs/templates/kops/default.yaml
* Make k8s LB private
* To protect k8s access from the outside
=> [kops] K8S private 

geodesic_apkindex.md5, rootfs/etc/profile.d/aws-vault.sh
- Upgrade Teleport to 3.2.4
- When syncing clocks, show results of sync
- Get support from `TELEPORT_SITE` and `TELEPORT_AUTH` environment variables.
- Previous version gave no feedback on successful sync of clock, giving impression that clocks were still out of sync
https://github.com/gravitational/teleport/pull/2675
=> [teleport] Upgrade Teleport to 3.2.4

codefresh/build.yml
* Use the normalized branch name
* Sometimes branches contain slashes or other bad characters for docker tags
=> [codefresh/build] Use the normalized branch name

.gitignore, rootfs/etc/init.d/atlantis.sh, rootfs/usr/local/bin/git-credential-github
* Add `rootfs/usr/local/bin/git-credential-github`
* Update `rootfs/etc/init.d/atlantis.sh` to use `git-credential-github`
* `git-credential-github` is useful for adding GitHub credentials to `git` to allow access to private GitHub repos
* When the `atlantis` server starts, execute `git-credential-github` to configure `git` with `atlantis` user and GitHub token to allow access to private repos
* https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage
=> Add `rootfs/usr/local/bin/git-credential-github`. Update `rootfs/etc/init.d/atlantis.sh` to use `git-credential-github`

rootfs/etc/init.d/atlantis.sh
* Force `git` to use HTTPS instead of SSH for `atlantis`
* Even when `git@github.com:` protocol is specified for private GitHub repos, `git` will rewrite the URLs to use HTTPS protocol, for which we can use `GITHUB_TOKEN` (instead of SSH keys) to authenticate with GitHub when accessing private repos from `atlantis`
* https://ricostacruz.com/til/github-always-ssh
=> Force git to use HTTPS instead of SSH for atlantis

rootfs/etc/init.d/atlantis.sh
* Add URL `ssh://git@github.com/` to `git config --global` for `atlantis`
* The URL "git@github.com:" is used by `git` (e.g. `git clone`)
* The URL "ssh://git@github.com/" is used by Terraform (e.g. `terraform init --from-module=...`)
* We need both
=> Add URL `ssh://git@github.com/` to `git config --global` for `atlantis`

packages.txt
* Pin helm version to `2.14.0`
* To be consistent about the packages version
=> [helm] Pin helm to 2.14.0

rootfs/etc/profile.d/_geodesic-config.sh, rootfs/usr/local/bin/annotate-namespace, rootfs/usr/local/bin/destroy-namespace, rootfs/usr/local/bin/helmctl
1. Add `destroy-namespace` command
1. Enhance customization trace to show excluded files as well as included files
1. Add `namespace annotate` to `helmctl` (_alpha quality_)
1. Support CI/CD cleanup of resources no longer needed
1. Provide visibility as to why even though some files in a directory are being loaded, others are not
1. Consolidate functions into fewer files/commands
=> Add destroy-namespace command

Dockerfile, packages.txt, rootfs/etc/direnv/rc.d/terraform
* Use an empty cache folder to initialize module
* Terraform 0.12 no longer allows initialization of folders with even dot files =(
* Example of how to use direnv with terraform 0.12
```
export TF_MODULE_CACHE=.module
mkdir -p ${TF_MODULE_CACHE}
```
=> Direnv with Terraform 0.12 

Dockerfile, codefresh/release.yml, geodesic_apkindex.md5, requirements.txt
- Update "latest" tag upon release
- Multiple updates, including updating `cloudposse/packages` from 0.90.0 to 0.116.0
- Ensure "latest" tag tracks latest release
- Bring in current tools
- closes #496
- closes #502 
- closes #504 
- closes #506 
- closes #507 
- closes #509 Security issue
=> Tool and Alpine Updates

rootfs/etc/direnv/rc.d/terraform
[direnv] Better detection of TF_PREFIX
Previous algorithm did not work under Atlantis
=> [direnv] Better detection of TF_BUCKET_PREFIX

rootfs/etc/direnv/rc.d/terraform
[direnv] Better detection of TF_BUCKET_PREFIX, use lowest level `/conf` dir, not highest
Atlantis operates under `/conf/atlantis/...`
=> TF_BUCKET_PREFIX: Lowest /conf dir, not highest

rootfs/usr/local/bin/grafana-db
Fix a typo/character substitution in `grafana-db`
Restore functionality of downloading ConfigMaps via URLs
=> [grafana-db] Fix typo

docs/codefresh-pipeline.md, rootfs/usr/local/bin/codefresh-pipeline, rootfs/usr/local/bin/grafana-db, rootfs/usr/local/bin/yaml-diff
1. Create `yaml-diff`
1. Create `codefresh-pipeline`
1. YAML files can vary wildly in textual representation but represent the same JSON data. The `yaml-diff` tools allows two YAML file to be compared for meaning, not textual representation.
1. Codefresh has a CLI tool, but pipeline specs exported by it have lots of information that is read-only, so you cannot directly create a pipeline from an exported pipeline spec. The `codefresh-pipeline` tool helps with that and other issues, providing a more friendly tools for downloading and uploading pipelines.
=> Create tools for mananging Codefresh pipelines

rootfs/usr/local/bin/codefresh-pipeline
[codefresh-pipeline] Give better error message when codefresh is not installed
`codefresh` is not installed in Geodesic by default, but `codefresh-pipeline` is. We want things to work sensibly in the default configuration, so `codefresh-pipeline` should explain why it is not working and what to do about it.
=> [codefresh-pipeline] Give better error message when codefresh is not installed

rootfs/usr/local/bin/destroy-namespace
Allow configuration of `helm` binary for `destroy-namespace`  by setting `HELM_BINARY` env var
Enable support for helm v2 and v3 at the same time in the same environment.
=> Allow configuration of helm binary for destroy-namespace

rootfs/usr/local/bin/destroy-namespace
[destroy-namespace] Use `--purge` with `helm` v2 `delete` but not with `helm` v3
`helm` v2 requires the `--purge` flag, but that flag was removed and the behavior made the default in `helm` v3.
=> [destroy-namespace] Use --purge with helm2 delete but not with helm3

rootfs/etc/syslog-ng/syslog-ng.conf
Update syslog-ng.conf to current version
`syslog-ng` was updated when we updated Alpine to 3.11, but it's config file was not, causing `syslog-ng` to issue warnings on startup. This resolves those warnings.
=> Update syslog-ng.conf to current version

rootfs/etc/profile.d/use-profile.sh
- Remove `use-profile.sh`
- Essentially dead code, as it calls a function removed in #368 and therefore emits an error message if it does anything
=> Remove reference to function removed in PR 368

Dockerfile
* Temporarily use `XDG_CONFIG_DIR`
* https://github.com/direnv/direnv/issues/595
=> fix direnv

rootfs/templates/bootstrap, rootfs/templates/wrapper
- If `APP_NAME` is set when Geodesic is installed, tag the running Docker container with `APP_NAME` instead of the Docker image name
- `APP_NAME` can be set to distinguish different forks of the same image. The distinction needs to be carried over to the container name, otherwise one fork's execution script will attach to the other fork's running container even though the `APP_NAME` is different.
=> Tag running Docker container with APP_NAME when set

rootfs/etc/profile.d/aliases.sh
- In helper function `chdo`, use `chamber env` instead of `chamber -f dotenv`
When `chdo` was written, `chamber` did not have the `env` option to export secrets into the environment, the closest thing it had was `chamber -f dotenv`. However, there are differences in how special characters like exclamation point (!) are handled, causing incorrect exporting of secrets when they had these special characters. `chamber` has since [added the `env` feature](https://github.com/segmentio/chamber/pull/184), and this PR uses that to ensure correct handling of special characters.
=> [chdo] Use `chamber env` instead of `chamber -f dotenv`

Dockerfile, codefresh/build.yml, requirements.txt, rootfs/etc/profile.d/aws.sh
- Enhance detection of AWS_PROFILE changes to keep prompt updated
- bump awscli from 1.18.69 to 1.18.91, closes #596 
- bump boto3 from 1.13.19 to 1.14.14, closes #597 
- bump ansible from 2.9.9 to 2.9.10, closes #598 
- bump google/cloud-sdk from 294.0.0-alpine to 299.0.0-alpine, closes #599
- Previously some changes to the environment would cause the AWS tools to use a different profile/role without the prompt reflecting the change
=> [aws] Enhance detection of AWS_PROFILE changes

rootfs/etc/profile.d/aws.sh, rootfs/etc/profile.d/geodesic.kube-ps1.sh, rootfs/etc/profile.d/set-cluster.sh, rootfs/usr/local/bin/eks-update-kubeconfig
- When trying to convert an AWS role ARN to an AWS profile name, consider the credentials file
- Use heuristics to shorten EKS cluster name
- When using a tool like `saml2aws`, your initial role ARN probably will not be in the AWS config file, but `saml2aws` adds it to the credentials file, so we look there, too
- More flexibility in the shortening algorithm provides better results for unexpected cases
Geodesic automatically installs a function to shorten the name of the Kubernetes cluster as it appears on the command line prompt. You can install a different function if you do not like the results. Set `KUBE_PS1_CLUSTER_FUNCTION` in your Dockerfile or `~/.geodesic/preferences`. Set `KUBE_PS1_CLUSTER_FUNCTION=echo` to disable shortening. '
- Customizing `kube_ps1`: …
=> [prompt] expand search for AWS profile, enhance cluster name shortening

rootfs/etc/profile.d/aws.sh
- [prompt] protect against multiple inclusions of same role ARN
- The prompt code scans for the current AWS IAM role (`aws sts get-current-identity`) in various files in order to map it to a friendly profile name. However, prior to this change, if it found it in more than one place, it would cause breakage. This fixes it so it only uses the first value found.
=> [prompt] protect against multiple inclusions of same role ARN

Dockerfile
- Do not delete Helm v2 plugin cache
- Cache is a misnomer, it is actually the only place Helm v2 plugins are kept
=> Helm v2 "cache" is actually "data"

rootfs/usr/local/bin/destroy-namespace
- [destroy-namespace] Fix Helm v3 compatibility
- Would otherwise likely not actually delete Helm v3 releases or even worse delete the wrong ones
=> [destroy-namespace] Fix Helm v3 compatibility

rootfs/usr/local/bin/aws-region, rootfs/usr/local/bin/helm3-metadata-fix
1. New command `helm3-metadata-fix` updates metadata that `helm 2to3 convert` fails to update
2. New command `aws-region` converts AWS Regions codes (e.g. `us-east-1`) to unique 3-character codes
1. After using `helm 2to3 convert` to migrate a Helm v2 release to Helm v3, the release is missing metadata that `helm` requires in order to make changes to the resources. `helm3-metadata-fix` updates the metadata for all the resources in the release so that `helm` will operate on them.
1. It is useful to include region names as part of an overall resource naming strategy, but it is also desirable to keep names short and keep semantic terms a consistent length.  `aws-region` is a tool you can use to freely convert between consistent 3-character codes (short and consistent length) and official AWS …
=> New commands aws-region & helm3-metadata-fix

Dockerfile
- Restore Atlantis access to Helm v2 Home
- Atlantis write access to Helm v2 was inadvertently removed in  #608
=> Restore Atlantis access to Helm v2 Home

rootfs/templates/wrapper
* Prefix `NAME`, `IMAGE` and `TAG` with `GEODESIC_`
* In some WSL2 instances at least, `NAME` seems to be a default variable that has the hostname, preventing the isolation of containers by their name as you'd normally expect from geodesic.  This allows situations where you can be running a container for one environment, say prod, and need to pop in to a staging container, but you will instead be added to a new shell in the existing prod variable.
* Namespacing these overly generic variable names will hopefully prevent some of that confusion
* Also, `GEODESIC_PORT` was already defaulted to the environment variable previously in the script, so it had two levels of overrides before.  Now just the one commonly namespaced one.
=> Prefix Wrapper Environment Variables with GEODESIC_

os/debian/packages-debian.txt
- Add iproute2 package for Debian
- Adds `ip` and `nstat`, needed by some other utilities
=> Add iproute2 package for Debian

os/alpine/Dockerfile.alpine, os/debian/Dockerfile.debian
- Add kubectl support to Debian version
- Is included in Alpine version, was left out of Debian version by mistake
=> Add kubectl support to Debian version

.github/draft-release.yml, .github/workflows/draft-release.yml, rootfs/etc/profile.d/aws-okta.sh, rootfs/etc/profile.d/aws-vault.sh
- Use release-drafter to automatically generate release notes combining multiple automatic upgrades and manual changes
- More consistent release notes more easily including all automated updates in a single release
- This does not automatically create a release, just draft the release notes. Releases are still done manually, and release notes and version numbers can be edited before release.
=> Use release-drafter to draft release notes

.github/draft-release.yml
- Fix broken syntax in `draft-release` config file
- Action would not execute because of syntax errors
=> [draft-release] Fix broken syntax in config file

.github/draft-release.yml
- Remove cruft from generated release notes
- Make release notes shorter and easier to read by removing irrelevant informaition
=> Remove cruft from generated release notes

.github/workflows/docker.yml
- Create docker image when release is "published"
- We had been creating the image when the release was "created" but we are now creating release drafts, and want to create the image when we finally publish the release. Use "release" type "published" instead of "release" so that images are built for published "pre-release" versions, too.
=> Create docker image when release is published

.github/draft-release.yml, rootfs/etc/profile.d/aws-vault.sh, rootfs/etc/profile.d/aws.sh, rootfs/usr/local/bin/aws-region
- [aws-vault] [aws] Enable assume-role via AWS SDK in most cases. Make`aws-vault` config available always. 
- [draft-release] Fix regex so release drafts do not eat multiple Renovate PRs
- [aws-region] Include short as well as fixed AWS availability zone abbreviations
- Better user experience when not using `aws-vault`: retain interactive role picker and automatic refresh of stale credentials
- Only the first of consecutive Renovate PRs was showing because of greedy regex
- Some people are using the short abbreviations from [`terraform-aws-utils`](https://github.com/cloudposse/terraform-aws-utils)
=> Enable assume-role via AWS SDK in most cases

.github/renovate.json
- Limit `aws` CLI and `boto3` updates to once a week and group them together
- Reduce the noise. In general these are updated several times a week but the updates are not urgent.
- Group them because they are typically released together (since `aws` depends on `boto3`) and `aws` pins `boto3` in such a way that the `boto3` update would break `aws` if `aws` is not updated at the same time.
=> Limit AWS CLI updates to once a week

.github/workflows/docker.yml, Makefile, os/alpine/Dockerfile.alpine, os/debian/Dockerfile.debian, os/debian/packages-debian.txt, requirements.txt, rootfs/etc/profile.d/banner.sh
- Include version number in Docker image
- Update Google Cloud SDK 316.0.0 -> 328.0.0
- Update `helm-2to3` 0.7.0 -> 0.8.1
- Pin Python `cryptography` package to 3.3.2 
- Add `net-tools` package do Debian
- Disable package repo hash check
- Show which version of Geodesic you are running
- Stay current
- Stay current
- Current version of `cryptography` does not build on Alpine: `No module named 'setuptools_rust'`
- Feature parity with Alpine image
- Purpose of hash check was to invalidate caches, but now that is done with Geodesic version number
=> Publish version number, freeze cryptography version, update Google Cloud SDK

.editorconfig, .github/renovate.json, os/alpine/Dockerfile.alpine, os/debian/Dockerfile.debian, requirements.txt, rootfs/etc/profile.d/aws.sh, rootfs/etc/profile.d/banner.sh, rootfs/etc/profile.d/helm.sh, rootfs/etc/profile.d/set-cluster.sh, rootfs/usr/local/bin/aws-region, rootfs/usr/local/bin/eks-update-kubeconfig
- Remove `ansible`
- Add `AWS_REGION_ABBREVIATION_TYPE` to set region abbreviations used in our tools
- Add `AWS_DEFAULT_SHORT_REGION` set to `$AWS_REGION_ABBREVIATION_TYPE` of  `$AWS_DEFAULT_REGION` 
- With that, better support for EKS clusters (`set-cluster`, `eks-update-kubeconfig` should not work out-of-the box for most users)
- Better error handling in `set-cluster` and `eks-update-kubeconfig` 
- Add support for region `ap-northeast-3` made available 2020-03-01
- Ensure `$KUBECONFIG` has mode `rw-------` before referencing it
- Updated support for initializing AWS configuration
- Configure Renovatebot to update Geodesic Dockerfiles
- Include Alpine patch version and Debian minor version in startup messages
- Updates:
- Alpine 3.12.1 -> 3.12.4
- Debian 10.6 -> 10.8
- Python (Debian …
=> Security updates, better EKS cluster support

.github/renovate.json
- [renovate] Remove invalid matchPaths from `renovate.json`
- #687 attempted to get Renovate to keep our Dockerfiles up-to-date by explicitly including them. The attempt not only failed, it broke the configuration, causing all updates to stop.
Renovate was already finding our Dockerfiles. It was not updating them because it will not update versions containing variables. As a result, we cannot rely on Renovate to keep the Dockerfiles up-to-date with respect to nearly anything in them, since we use variables for all versions (not just `FROM` but also Go SDK, `helm` plugins, etc.).
=> [renovate] Remove invalid matchPaths

os/alpine/Dockerfile.alpine, os/debian/Dockerfile.debian, rootfs/etc/profile.d/_preferences.sh, rootfs/etc/profile.d/aws.sh, rootfs/usr/local/bin/boot
- Better user experience when running via docker CLI
- No change to `make install` behavior
- Current experience when user naïvely runs Geodesic is that it outputs a script to generate a launch wrapper, which is very confusing
- Backwards compatibility
```
$ docker run -it --rm -v $HOME:/localhost cloudposse/geodesic:latest
⧉  geodesic 
✗ . [none] ~ ⨠ 
```
```
$ docker run --rm cloudposse/geodesic:latest
########################################################################################
########################################################################################
```
```
$ docker run -it --rm cloudposse/geodesic:latest
########################################################################################
* No filesystem is mounted at /localhost which limits Geodesic …
```
=> Better user experience when running via docker CLI

Dockerfile.options, os/alpine/Dockerfile.alpine, os/debian/Dockerfile.debian, requirements.txt
- Update Debian to use AWS CLI v2 by default. 
- Remove Jinja2. Supersedes and closes #705.
- Update Alpine 3.13.4 -> 3.13.5
- Update Google Cloud SDK 334.0.0 -> 342.0.0
- AWS now recommends using CLI v2, and v2 is required when using AWS SSO for authentication, which Cloud Posse now recommends
- Jinja2 released a new major version (3.0), potentially causing problems. We believe the only thing using Jinja2 was `ansible`, which we dropped a while back, so we are removing it completely to save space and maintenance. Users can, of course, add it back in their derived Docker images.
- Update Alpine and Google Cloud SDK to current versions (updates not handled by Renovate)
Alpine was not updated to use AWS CLI v2 because the official distribution does not support Alpine, because Alpine does …
=> Update Debian to AWS CLI v2

rootfs/etc/motd, rootfs/sbin/docker, rootfs/templates/wrapper, rootfs/usr/local/bin/install-docker-command, rootfs/usr/local/bin/wrapper
- Fix #739 provide OS-specific instructions for installing `docker`
- Previously, Geodesic provided instructions for installing `docker` on Alpine, even if it was running under Debian.
=> Fix #739 provide OS-specific instructions for installing docker

README.md, os/alpine/Dockerfile.alpine, os/debian/Dockerfile.debian, packages.txt, rootfs/etc/init.d/atmos.sh, rootfs/etc/profile.d/_workdir.sh, rootfs/etc/profile.d/atmos.sh, rootfs/etc/profile.d/prompt.sh, rootfs/templates/wrapper
- When starting Geodesic, set the initial working directory to the Host's current working directory, if it is accessible
- If the initial working directory appears to be part of an `atmos` configuration, set `ATMOS_BASE_PATH` accordingly
- Allow fine-grained customization of command line prompt
- Update `kubectl` 1.16 -> 1.21
- Update Google Cloud SDK 352.0.0 -> 369.0.0
- Update Debian 10.10 -> 10.11
- Update Python3 on Debian 3.8.11 -> 3.8.12 
- Update Alpine 3.13.5 -> 3.13.7 (Python3 3.8.10 dictated by Alpine package repo)
- Popularly requested features
- Outdated `kubectl` should have been upgraded long ago
- Security updates
- closes and supersedes #755 
- replaces #753, #754
- https://github.com/cloudposse/atmos/pull/100
- Augments response to #417 
You could previously choose …
=> Start in host CWD, autoconfigure ATMOS_BASE_PATH

rootfs/etc/profile.d/_workdir.sh, rootfs/etc/profile.d/atmos.sh, rootfs/etc/profile.d/banner.sh
- Notify user when Geodesic cannot distinguish host file system from container file system by device name and fall back to parsing file system path.
- Distinguish AMD CPU from Apple M1
- Configure `atmos` auto-completion when `atmos` is installed.
- On Fedora, for example, the host and container filesystems are on the same device. This means we cannot tell if another host path was bind mounted or not. In this situation, we fall back to reporting that files under `/localhost` are on the HOST and other files are not, which was the test we were previously. (The newer device-based test is to support developers who keep their development file tree outside of their home file tree.)
- We warn users about trying to run Geodesic on Apple M1, but the warning was being displayed when running on …
=> Configure atmos auto-completion, verify host filesystem detection

rootfs/templates/bootstrap
Fix non-portable constructs so that Geodesic build, install, and run work on as many hosts as possible
- Replace path equivalency testing with file equivalency testing, because the `-ef` test is specified in POSIX but `realpath` is not and is not that widely distributed (competes withe `readlink`).
=> Portability fixes

os/alpine/Dockerfile.alpine, os/alpine/packages-alpine.txt, os/alpine/rootfs/etc/syslog-ng/syslog-ng.conf, os/debian/Dockerfile.debian, os/debian/rootfs/etc/profile, rootfs/etc/profile.d/_30-geodesic-config.sh, rootfs/etc/profile.d/aws.sh, rootfs/etc/profile.d/banner.sh, rootfs/etc/profile.d/prompt.sh
- Copy Alpine `PATH` initialization to Debian, replacing Debian behavior of clobbering preexisting `PATH`
- Update Debian 11.3 -> 11.4
- Update Alpine 3.15.4 -> 3.16.2
- Miscellaneous cleanups
- Debian behavior is to ignore any existing value of `PATH` environment variable when launching `bash` and set it to a predefined value. This makes it impossible to set the `PATH` in the Dockerfile. Alpine's approach (taken from Arch Linux) is to append the path components to any existing `PATH` value, allowing users to set a preferred path, but still ensuring that all expected/required directories are included in `PATH` to start.
- Keep up-to-date
- Clean up little things that were nevertheless irritating
- Supersedes and closes #790 
- Supersedes and closes #799
=> Update Debian, Alpine, etc, Preserve PATH

rootfs/usr/local/bin/codefresh-pipeline, rootfs/usr/local/bin/grafana-db, rootfs/usr/local/bin/helm3-metadata-fix
- Update scripts for `yq` v4 CLI changes
- Some of our shell scripts use [yq](https://github.com/mikefarah/yq/), but the options and commands changed significantly from v2 (current when the scripts were written) to the now current (and installed in Geodesic) v4, causing the scripts to break. This PR updates the scripts to work with `yq` v4.
- https://mikefarah.gitbook.io/yq/
- Supersedes and closes #806
=> Update scripts for yq v4 CLI changes

packages.txt, rootfs/etc/ssh/ssh_config
- Configure SSH to use AWS Session Manager for connectivity to instances
- Install `zip`
- AWS Session Manager allows for connectivity without requiring any inbound port access
- Standard tool required for creating certain AWS resources among other things
- https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html
=> Configure SSH for AWS Session Manager, add zip

requirements.txt
- Remove obsolete `boto` (replaced with `boto3`)
- `boto` requires Python 2 and installs dependencies that require Python 2 but we no longer install Python 2 so `boto` is just extra broken cruft.
- Boto: [PyPi](https://pypi.org/project/boto/) [GitHub](https://github.com/boto/boto)
- Boto3 [PyPi](https://pypi.org/project/boto3/) [GitHub](https://github.com/boto/boto3)
=> Remove obsolete `boto` (replaced with `boto3`)

os/alpine/Dockerfile.alpine, os/debian/Dockerfile.debian, packages-amd64-only.txt, packages.txt, rootfs/usr/local/bin/no-arm64-support
- For tools we have been including in Geodesic but that do not have `arm64` support:
- Install the tool in the `amd4` versions of Geodesic
- Install a stub script that explains the tool is missing due to lack of support
* In #837, we removed all the tools without `arm64` support from both versions. However, those tools are used by scripts and commands we continue to include, and we do not know how important those are to the Geodesic community. This way, they will continue to work as before for `amd64` versions and will generate meaningful error messages (instead of generic "command not found" errors) in the `arm64` version.
=> Install stubs for tools missing arm64 support

.github/workflows/docker.yml
Since Geodesic v1.8.0 we have published Docker images to `public.ecr.aws/cloudposse/geodesic` as well as Docker hub `cloudposse/geodesic`. However, due to a bug in our script, the `latest` tag was only being pushed to `public.ecr.aws` and Docker hub `latest` was stuck at `1.7.0-alpine`. 
When Geodesic v2.0.0 was released, we started tagging the Debian image as `latest` instead of the Alpine image, but due to the above bug, that only affected the `public.ecr.aws` repo, not the Docker hub rep. With this release, we restore updates of the `latest` tag to Docker hub, and consequently shift latest from Alpine to Debian there, too.
- #825
=> Publish "latest" image to Docker hub

rootfs/templates/wrapper
- Remove `--quiet` option from Docker command that checks if Geodesic is already running
- Starting with Docker CLI version 24.0.0, the `--quiet` option overrides the `--format` option. For backward compatibility, we prefer to continue to use the `--format` option, even thought the format is that same as that produced by v24 `--quiet`. 
Resolves warning on starting Geodesic:
```
WARNING: Ignoring custom format, because both --format and --quiet are set.
```
=> Remove redundant --quiet option from docker command

.github/workflows/label.yml
- Update labeler from v2.1.0 to v4
- Labeler version prior to v4 run on obsolete node12.
- Runners use [node16](https://github.blog/changelog/2021-12-10-github-actions-github-hosted-runners-now-run-node-js-16-by-default/)
- [Labeler update](https://github.com/actions/labeler/releases/tag/v4.0.0) for node16
=> Update labeler from v2.1.0 to v4

os/alpine/Dockerfile.alpine, os/alpine/packages-alpine.txt, os/alpine/rootfs/etc/syslog-ng/syslog-ng.conf, os/debian/Dockerfile.debian, packages.txt, rootfs/usr/local/bin/kubectl-auto-select
- Enhance `kubectl-auto-select` to work with Debian
- Configure Debian version by codename
- Upgrade Alpine to use Fuse 3
- For Alpine, configure `bindfs` version via Docker `ARG` and upgrade `bindfs` v1.15.1 -> 1.17.6
- Upgrade Python on Debian from v3.10.10 to v3.11.6
- Upgrade Google Cloud SDK v422.0.0 -> 455.0.0
- Upgrade `kubectx` v0.9.4 -> v0.9.5
- Upgrade `helm-diff` v3.6.0 -> v3.8.1
- `kubectl-auto-select` was written for Alpine and failed on Debian due to differing package managers
- Python is configured by Debian codename, so keep it in sync with Debian by using codename is both places
- Debian upgraded to Fuse 3 in v11 "bullseye" so keep Alpine relatively in sync
- Alpine `bindfs` version was hard coded, but not easily changed, and was old. Debian installs `bindfs` via package, …
=> Non-automatic tool updates

.github/workflows/label.yml, os/debian/Dockerfile.debian, rootfs/etc/profile.d/_20-localhost.sh, rootfs/etc/profile.d/user.sh, rootfs/templates/wrapper
This PR fixes an issue with using `bindfs` to work around file ownership issues caused by running the Docker daemon as root (#594). This support is provided as a courtesy, but the better solution is to [run Docker in "rootless" mode](https://docs.docker.com/engine/security/rootless/), which is done automatically when you use [Docker Desktop](https://docs.docker.com/desktop/). Support for running Docker as `root` should be considered deprecated.
- Use bi-directional UID and GUID mapping in `bindfs` mount of host filesystem
- Remove host username (`$USER`) from Geodesic environment
- To guard against [CVE-2022-24765](https://nvd.nist.gov/vuln/detail/cve-2022-24765), `git` checks the ownership of all directories it looks at for configuration, and complains if it finds a directory with a …
=> Make bindfs mapping bidirectional, remove host USER name from env

.github/workflows/label.yml
- Add explicit permissions to labeler
- Labeler needs write permission to update labels, which was previously granted by default but now must be explicit
=> Add explicit permissions to labeler

README.md, README.yaml
- Emphasize current Geodesic version over historical versions
- Remove remnants of explanation of why Geodesic was not supporting Apple Silicon
- Make documentation of historical changes more concsise
- Give the most relevant information first
- Make historical information easier to understand
=> Clean up narrative of Geodesic history

.github/workflows/docker.yml, Makefile, os/alpine/Dockerfile.alpine, os/debian/Dockerfile.debian
- Add OCI annotations to published images
- Standard compliance and better support for third-party tooling
- [OCI annotations](https://specs.opencontainers.org/image-spec/annotations/)
- Supersedes and closes #915
=> Add OCI annotations

packages-amd64-only.txt, packages.txt, rootfs/usr/local/bin/no-arm64-support
- Add [rakkess](https://github.com/corneliusweig/rakkess) to `linux/arm64` Debian build
- Previously we excluded `rakkess` from the `arm64` build because there was no binary available and it was not considered that useful a tool. However, with AWS now supporting a [new mechanism for access control for EKS clusters](https://github.com/aws/containers-roadmap/issues/185#issuecomment-1862970742), it is newly useful in verifying access control given that it access can no longer be determined by simply looking at Kubernetes resources.
- https://docs.aws.amazon.com/eks/latest/userguide/access-entries.html
- https://github.com/corneliusweig/rakkess
- Some of the best documentation is in [this issue comment](https://github.com/aws/containers-roadmap/issues/185#issuecomment-1863025784)
=> Add rakkess to linux/arm64 in Debian

packages.txt, rootfs/etc/codefresh/require_vars, rootfs/etc/profile.d/_07-term-mode.sh, rootfs/etc/profile.d/_10-colors.sh, rootfs/etc/profile.d/_30-geodesic-config.sh, rootfs/etc/profile.d/_40-preferences.sh, rootfs/etc/profile.d/aws.sh, rootfs/etc/profile.d/prompt.sh, rootfs/etc/profile.d/terraform.sh, rootfs/etc/profile.d/Ω_finalize.sh, rootfs/etc/profile.d/Ω_overrides.sh, rootfs/usr/bin/docker, rootfs/usr/local/bin/boot, rootfs/usr/local/bin/codefresh-pipeline, rootfs/usr/local/bin/eks-update-kubeconfig, rootfs/usr/local/bin/grafana-db, rootfs/usr/local/bin/kubectl-auto-select, rootfs/usr/local/bin/no-arm64-support, rootfs/usr/local/bin/yaml-diff
This release brings preliminary support for "dark mode" terminals, and a simplified option for a Terraform workspace prompt. If you find problems, please report them, but we expect the situation will at least be no worse than before.
Mainly, with respect to dark mode terminals, after setting a text color, we do not "revert" by setting the text to black, we now revert by setting foreground and background to terminal defaults.
Similarly, after setting text to bold, we no longer reset all graphics settings, we just unset bold. If this causes a problem in your terminal, you can revert the behavior by setting the environment variable `TERM_BOLD_OFF=$(tput sgr0)` inside Geodesic. 
Geodesic has a legacy option for displaying the current Terraform workspace when in a directory with `*.tf` files. …
=> Initial support for dark mode terminals

rootfs/etc/profile.d/_07-term-mode.sh, rootfs/etc/profile.d/_10-colors.sh, rootfs/etc/profile.d/prompt.sh, rootfs/etc/profile.d/terraform.sh
- Fix caching of terminal escape codes
- Update `update-terminal-mode` command to allow forcing a mode
- rename internal `update_terraform_prompt` to `_update_terraform_prompt`
- Substantial performance improvement on every command line prompt
- Auto-detection is likely to be unavailable or wrong on some terminals
- Keep internal functions from showing up in command line completions
=> Dark mode caching fix

.github/workflows/draft-release.yml, Dockerfile.custom, Dockerfile.options, Makefile.custom, docs/logo.md, os/alpine/Dockerfile.alpine, os/alpine/requirements.txt, os/debian/Dockerfile.debian, os/debian/rootfs/etc/apt/preferences.d/kubectl-preferences, packages.txt, requirements.txt, rootfs/usr/local/bin/grafana-db
- Google Cloud SDK is no longer pre-installed. The Google Cloud Debian package repository is installed, so you can install it into Debian with `apt-get`. 
- AWS CLI v1 is no longer installed in Debian. The CLI v2 has been the default for Debian Geodesic for almost 3 years, so this should impact many people, if any.
- Python dependencies of AWS CLI v2 (including `boto3`) are also no longer pre-installed on Debian. 
- Update repository default branch name `master` -> `main`
- Google Cloud SDK is no longer installed
- Update Debian 12.4 -> 12.5
- Update Python 3.12.2 -> 2.12.3
- Add [OpenTofu Debian package repository](https://opentofu.org/docs/intro/install/deb/)
- Pin `kubectl` package to Cloud Posse repository over Google Cloud SDK repository
- Update `bindfs` on Alpine 1.17.6 -> 1.17.7
- …
=> Update Dependencies, add OpenTofu package repo

rootfs/etc/profile.d/aws.sh
- Fix colorized text added to prompt without delimiters for color codes by `aws.sh`
- Bash counts the characters in the prompt to manage viewing and editing command history. Non-printing characters must be delimited so they are not counted in the prompt text length.
=> Fix colorized string in prompt

.github/renovate.json
- Migrate Renovate configuration (from base of `config:base` to `config:recommended`) per **validator**
- Mend Renovate recommended update
- https://docs.renovatebot.com/release-notes-for-major-versions/#breaking-changes-for-36
=> Migrate Renovate configuration (base -> recommended) per validator

.github/renovate.json
- Configure Renovate to Ignore updates to Alpine version of Geodesic
- No longer supporting Alpine
=> Ignore updates to Alpine

os/debian/Dockerfile.debian, rootfs/templates/bootstrap
- Update Debian 12.5 -> 12.6
- Update Python 3.12.3 -> 3.12.4
- Update [kube-ps1](https://github.com/jonmosco/kube-ps1) 0.8.0 -> 0.9.0
- Update [helm-diff](https://github.com/databus23/helm-diff) 3.9.4 -> 3.9.9
- Update [helm-git](https://github.com/aslafy-z/helm-git) 0.15.1 -> 1.3.0
- Update bootstrap `gomplate` template to use `strings.Split` instead of deprecated `split`
- Update all unpinned packages to latest released versions
- Updates [OpenTofu](https://opentofu.org/) 1.7.1 -> 1.7.3
- Keep current
=> Update dependencies and tools

os/debian/Dockerfile.debian, rootfs/templates/bootstrap
- Update Python 3.12.4 -> 3.12.5
- Update Debian 12.6 from 20240722 to 20240812
- Fix conversion of `gomplate` `split` to `strings.Split` done wrong in #953 
- Stay current
- Fix #954
=> Update Python to 3.12.5, fix init script

os/debian/Dockerfile.debian, rootfs/etc/profile.d/aws.sh
- Restore symbolic link in `$HOME` to `.aws`
- Update Debian 12.6 -> 12.7
- Update Python 3.12.5 -> 3.12.7
- Update `helm-diff` 3.9.9 -> 3.9.11
- Fixes #958 
- Routine updates to current versions
=> Fix ~/.aws symlink

os/debian/Dockerfile.debian, packages.txt, rootfs/etc/profile.d/_10-colors.sh, rootfs/etc/profile.d/aws.sh, rootfs/etc/profile.d/chamber.sh
- Fix the script for converting the current AWS IAM role to something short and meaningful for the shell command prompt
- Add support for converting Identity Center Permission Sets to profile names in the shell prompt
- Support setting `CHAMBER_KMS_KEY_ALIAS` via `CHAMBER_KMS_ALIAS`
- Add the `lsb-release` package to provide `lsb_release`
- The code was buggy due too piecemeal changes resulting in unreachable code
- Many people are using Identity Center now
- Setting `CHAMBER_KMS_KEY_ALIAS` as is customary in Cloud Posse Dockerfiles triggers the `SecretsUsedInArgOrEnv` warning. While this is arguably a bug in the warning, this change allows concerned users to avoid the issue.
- Some tool installation scripts require `lsb_release` to be already installed
- `chamber` [KMS key …
=> Fix Role Prompt, bypass buggy secrets check, add lsb_release

rootfs/etc/init.d/bootstrap.sh, rootfs/templates/bootstrap, rootfs/usr/local/bin/boot
- Fix manual install to use `APP_NAME` and `INSTALL_PATH` properly
- When installing without the Makefile, displayed instructions and resulting install did not work
=> Fix manual install to use APP_NAME and INSTALL_PATH properly

rootfs/templates/wrapper-body.sh, rootfs/usr/local/sbin/shell-monitor
- Fix shell monitoring introduced in v4.1.0 #970 
- Fix `--solo` / `ONE_SHELL=true` option broken in v4.1.0 #970 
- Bug caused shell monitor to burn CPU busy waiting on shell exits rather than sleep and poll
- Oversight in refactoring launch vs exec parameters left out terminal allocation for `--solo` option, causing Geodesic to immediately exit
=> Fix Excessive CPU usage, fix --solo

ReleaseNotes-v4.md, docs/environment.md, rootfs/etc/profile.d/_01-launch-warning.sh, rootfs/etc/profile.d/_60-register-stray-shells.sh, rootfs/templates/wrapper-body.sh, rootfs/usr/local/bin/boot
- `GEODESIC_DOCKER_EXTRA_ARGS` is deprecated. Geodesic distinguishes between options for launching a container
and options for exec’ing into a running one. Use `GEODESIC_DOCKER_EXTRA_LAUNCH_ARGS` for container launch and
`GEODESIC_DOCKER_EXTRA_EXEC_ARGS` for exec’ing into a running container.
- Add additional outputs to `--verbose` mode
- Minor cleanups for non-standard launch attempts
- Some arguments only apply at launch time, while others my vary with each exec into the same container
- More clarity around options being passed to docker
- Catch a few more edge cases
=> Split extra args into launch and exec
