README.md, docs/examples.md, rootfs/etc/profile.d/defaults.sh, rootfs/opt/geodesic, rootfs/usr/local/include/toolbox/Makefile, rootfs/usr/local/include/toolbox/kops/Makefile
* fix wrong path for `env.sample` file
* validate `SOA` for dns zone is short
* delete container and images on uninstall
* long TTLs for SOA record cause problems due to negative caching 
@goruha
=> Fix Cloud Create

Dockerfile
* Upgrade to helm 2.2.3
* Critical bug fixes: https://github.com/kubernetes/helm/releases/tag/v2.2.3
@goruha
=> Upgrade to helm 2.2.3

Dockerfile
* Updated helm version to the latest 2.3.1
* We need to use nice templating functions that supported in helm >= 2.3.0
=> Update helm to latest version

rootfs/usr/local/include/toolbox/Makefile
* Fix bootstrap make target
* It is required step for cluster create
=> Fix bootstrap script

Dockerfile, rootfs/usr/local/include/terraform/init, rootfs/usr/local/include/terraform/plan
* Upgrade terraform to 0.9.4
* Change `remote state` to `init` (`remote config` deprecated)
* Maintenance
=> Update to Terraform 0.9.4

rootfs/etc/profile.d/defaults.sh, rootfs/usr/local/include/terraform/init, rootfs/usr/local/include/toolbox/config/Makefile
* support `use-profile` 
* see: https://github.com/cloudposse/aws-assumed-role/pull/15
* https://github.com/cloudposse/aws-assumed-role/pull/15
=> Support profiles without assumed roles

Dockerfile
* Upgrade terraform to version 0.9.5
* https://github.com/hashicorp/terraform/issues/14140
=> Upgrade to TF 0.9.5

Dockerfile
* Pin terraform version to 0.9.11
* Would like to have bug fixes and features from new version
=> Upgrade Terraform to Version 0.9.11

.travis.yml
- added conditions to steps related to secured data
- travis do not send encrypted variables to untrusted PR's (from forked repo's)
=> Travis pr fix

Dockerfile, README.md
* Add `ansible` with utilities
* Facilitate automation of legacy systems (e.g. non-kubernetes!)
@osterman
=> Add Ansible with utilities

Dockerfile
* Bump terraform version to 0.10.1
* Get ability to use latest terraform features
=> Bump terraform version to 0.10.1

Dockerfile
* Updated Terraform version to `0.10.2`
* Bug fixes
* https://github.com/hashicorp/terraform/blob/v0.10.2/CHANGELOG.md
=> Update Terraform version to `0.10.2`

Dockerfile
* Added `sshpass`
* We need this feature for Ansible login to a remote host
=> Added `sshpass`

Dockerfile
* Update `Terraform` to `0.10.5`
* Bug fixes, new features, improvements
* https://github.com/hashicorp/terraform/blob/v0.10.5/CHANGELOG.md
=> Upgrade to Terraform 0.10.5

Dockerfile
* Update `Terraform` to the latest version `0.10.7`
* We want to use the latest Terraform features
=> Upgrade `Terraform` version to `0.10.7`

Dockerfile, README.md
* Add `packer`
* `packer` required for module https://github.com/cloudposse/terraform-aws-vault
=> Add packer

Dockerfile, README.md, rootfs/templates/kops/default.yaml, rootfs/usr/local/include/toolbox/config/Makefile
* Replaced `s3fs` with `goofys`
* Updated `README`
* `goofys` is better alternative to `s3fs` written in `Go` that natively supports assumed roles
* https://github.com/kahing/goofys
=> Swap out s3fs with goofys

rootfs/templates/scaffolding/Makefile
* Pass `DOCKER_IMAGE` and `DOCKER_TAG` to the installer from the `Makefile`
* Ensure that the installed version matches the one being developed
=> Install script corresponding to repo/tag in Makefile

Dockerfile
* Add `github-helm` plugin
* Easily install helm plugins from any github repo
=> Helm GitHub plugin

rootfs/usr/local/include/toolbox/config/Makefile
* Force `unmount`
* The `ssh-agent` and other processes hold on to files
* No easier way to handle this case
* https://github.com/cloudposse/geodesic/issues/90
=> Fix unmount

Dockerfile
* Update helm version to 2.7.2
* Fix bugs
=> Update helm version to 2.7.2

Dockerfile
* Upgrade to `kops` version `1.8.0`
* Upgrade to `kubectl` version `1.8.7`
* Maintenance
=> Upgrade to Kops 1.8.0, Kubectl 1.8.7

.travis.yml, Dockerfile
* Upgrade `helm`
* Upgrade `terraform`
* Upgrade `gomplate`
* Upgrade `goofys`
* bug fixes
=> Upgrade releases

Dockerfile, README.md
* Add `chamber` to easily manage secrets on AWS SSM+KMS
* Alternative strategy to manage secrets vs using S3 (via `goofys`)
=> Add chamber

README.md
* Updated `README.md` to mention `aws-vault`
* Recently added to the toolchain
=> Add aws-vault to README.md

Dockerfile, README.md
* Add `helmfile`
* Decompose helm plugin installation from helm installation
* Added `sops` for `helm-secret`
* Added `helm-secret` for encrypted secrets with `helmfile`
* Added `coreos-stable` helm repo
* Added official `incubator` helm repo
* Helmfile will make it easy for us to 12-factorize helm values and deploy chart collections
=> Add helmfile

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST.md
* Added `PULL_REQUEST.md` template
* Added `ISSUE_TEMPLATE.md` 
* Enforce consistency of PRs & Issues
=> Add PR template & Issue template

Dockerfile, conf/kops/helmfile.yaml, conf/kops/values/chart-repo.yaml, conf/kops/values/chartmuseum.yaml, conf/kops/values/nginx-ingress.yaml
* Add opinionated, kops-specific `helmfile.yaml` that defines all standard services
* make it easy to get clusters up and running quickly
=> Add master helmfile

Dockerfile
* Add `terragrunt`
* Use `APK_PACKAGES` arg to define native packages
* Terragrunt will make it easier for use to reuse terraform root-modules
=> Add terragrunt

Dockerfile
* Add `ncurses`
* Need `tput` for `kubectx` and `kubens`
=> Add ncurses

rootfs/conf/kops/helmfile.yaml
* Added fluentd to datadog logs forward
* Allow to collect logs to datadog
WIP till official PR would be merged https://github.com/kubernetes/charts/pull/5357
=> Add Datadog Log Forwarding with Fluentd

Dockerfile
* remove extraneous line-continuation (\) char
* Invalid `Dockerfile` syntax
=> remove extraneous line-continuation (\) char

rootfs/etc/profile.d/prompt.sh
* Add support for a "plain" prompt 
* UTF8 glyphs break some peoples terminals
Fixes #150
=> geodesic_prompt(): add PROMPT_STYLE handler

Dockerfile
* Upgrade to latest release of `cloudposse/packages`
* Incorporate new `helmfile` update
=> Upgrade packages

rootfs/conf/kops/kiam/Makefile, rootfs/conf/kops/kiam/README.md
=> Update kiam docs

rootfs/etc/profile.d/prompt.sh
* Only call `kill -WINCH $$` when dimensions of screen change
* Theory is that it contributes to this error... ![image](https://user-images.githubusercontent.com/52489/43626388-7ef7d118-96a6-11e8-929d-38c409f201e1.png)
* I suspect it could be related to bash not responding to `kill -WINCH $$` within some kind of deadline
=> Strategically signal bash to resize

rootfs/etc/profile.d/ssh-agent.sh
* Trap ^C and cleanup
* Previously, calling ^C would abort all subsequent profile scripts
=> Trap ^C When Prompting for SSH PW

rootfs/etc/profile.d/_colors.sh, rootfs/etc/profile.d/aws-vault.sh, rootfs/etc/profile.d/prompt.sh
* Define `red`, `green`, `yellow` and `cyan` color functions
* Make it easier to colorize output to call attention to important commands
=> Colorize messages

rootfs/usr/bin/s3fs, rootfs/usr/local/bin/s3
* Check that `/dev/fuse` is writable
* Sometimes `--privileged` mode will not be enabled in which case FUSE won't work
* CI/CD with Codefresh
=> Check for fuse

rootfs/etc/profile.d/oathtool.sh
* Add function that emits TOTP MFA code
* Useful for CI/CD and demos
=> Add MFA Helper Function

Dockerfile
* Add `helm diff` plugin
* See what changes are pending before calling `helmfile sync`
* CI/CD
* https://github.com/databus23/helm-diff/issues/87
=> Add helm diff

rootfs/etc/profile.d/prompt.sh, rootfs/etc/profile.d/terraform.sh
* Add terraform autocompletion to bash 
* Better UX
=> Add terraform autocompletion

Dockerfile
* Update packages version
* To get new versions of `helm` and `helmfle`
=> Pin packages version

Dockerfile, requirements.txt
Switch to the HTTPS alpine apk repositories
#249
=> apk: use https fastly repositories

rootfs/templates/kops/default.yaml
- add additional cluster policy
- add cloudLabels
#242
=> [kops] add autoscaler support

Dockerfile
* Add `helm-push` plugin (e.g. `helm plugin install https://github.com/chartmuseum/helm-push`)
* https://github.com/cloudposse/geodesic/issues/270
=> [helm] Add helm-push plugin

Dockerfile
* Update `packages` version
* Latest version of `kubectl`
=> Update `packages` version

packages.txt
* Restore aws vault
* Was accidentally reverted in #295
=> Restore aws-vault

Dockerfile, packages.txt
* Use alpine packages everywhere possible
* Better version management
=> Use apks for all packages

packages.txt, rootfs/etc/profile.d/aliases.sh
* Add `telnet`
* For us old-timers who prefer this for debugging than `nc` or `ncat`
=> Add telnet

Dockerfile
* Configure terraform to use persistent cache folder for plugins
* Speedup terraform inits
* Fixes #312
=> Configure cache directory

Dockerfile, packages.txt
* Install `bats-core` from [alpine community managed package](https://pkgs.alpinelinux.org/package/edge/community/x86_64/bats)
* Prefer to use proper package management over `git clone`
=> Install bats from alpine community repo

.dockerignore, requirements.txt
* Add `.dockerignore` to exclude certain files/directories from being sent over to the docker daemon
* Speed up docker builds
=> [.dockerignore] add file

packages.txt
* Add new packages 
* `terrahelp` to mask terraform output
* `scenery` to beautify terraform output
* `variant` for a modern task runner
=> add scenery, variant and terrahelp

packages.txt, public/motd
* Add `tfmask`
* Easily mask sensitive values in `terraform plan` or `terraform apply`
=> [tfmask] add package

packages.txt
* Update `tfmask` to `0.2.0`
* Support better masking of tf output
=> [tfmask] upgrade to 0.2.0

Dockerfile, packages.txt, rootfs/etc/profile.d/aws-okta.sh, rootfs/etc/profile.d/aws-vault.sh, rootfs/etc/profile.d/banner.sh, rootfs/etc/profile.d/motd.sh, rootfs/etc/profile.d/prompt.sh, rootfs/etc/profile.d/syslog-ng.sh
* Add support for `aws-okta` by segentio (requires `apk add aws-okta@cloudposse` to work)
* Support alternative ways to assume role
=> Add okta support

rootfs/etc/profile.d/fzf.sh
* Fix error when attempting to create link twice
* Entering into a subshell (e.g. with `assume-role`) would emit an error about the target already existing
=> [fzf] Create symlink conditionally

rootfs/etc/profile.d/aws-vault.sh
Minor tweaks to `aws-vault.sh` to provide better output and avoid unnecessary work.
Better performance
=> [aws-vault] Improve output and speed up

rootfs/usr/local/bin/codefresh-settings
* Update `codefresh-settings` 
* To support https://github.com/cloudposse/charts/pull/195
=> Updated codefresh-setting to support codefresh-service-account

rootfs/etc/profile.d/aws.sh, rootfs/etc/profile.d/terraform.sh
[profile.d/aws.sh] and [profile.d/terraform.sh] 
search for binaries to install autocompletion. 
Closes #352
=> [profile.d/aws.sh] [profile.d/terraform.sh]  search for binaries to install autocompletion

README.md, README.yaml
* Add animated screen capture (svg) to demonstrate the interactive component of geodesic
* Make it easier to see the utility of geodesic
* https://github.com/cloudposse/geodesic/blob/add-demo/README.md#screenshots
=> Add Screen capture

rootfs/usr/local/bin/helmctl
* Add `parameters` section
* Not sure how it got dropped
=> [helmctl] Add missing key

codefresh/build.yml, rootfs/etc/profile.d/aliases.sh
* Restore tests
* Lost when we moved from travis to codefresh in #470
=> [coderesh/build] Add tests

README.md, README.yaml
* Add slack archive link
* Show community activity
=> Add slack archive

rootfs/usr/local/bin/grafana-db
[grafana-db] Handle local files and other cleanups
Make it easier to move dashboards between Grafana instances
=> [grafana-db] Handle local files and other cleanups

.github/workflows/docker.yml, rootfs/etc/profile.d/prompt.sh
- [prompt] Improve HOST detection to show that you are operating in a host directory even if aliased by symbolic links
- Switch to matrix build
- Critical to know if you are working on files inside the container versus on the host
- Speed up build time by doing builds in parallel rather than in sequence
=> [prompt] Improve HOST detection, switch to matrix build

README.md, README.yaml
1. Updates README information to remove older, broken links and only link out to our "Getting Started with Geodesic" Guide.
1. Closes #689
=> Updates README to fix #689

docs/customization.md
- fix agreement 
- correct spelling
=> (docs) update docs/customization.md

docs/design.md
- update spelling
- update agreement
- correct capitalization
- remove redundancy
=> (docs) update docs/design.md

.github/workflows/docker.yml
* Adds ECR Builds
* Occasionally get dockerhub rate limited, public ECR fixes that
=> ECR Builds

.github/labeler.yml, .github/workflows/docker.yml, .github/workflows/draft-release.yml, .github/workflows/label.yml, .github/workflows/validate-codeowners.yml, .github/workflows/vhs.yaml, README.yaml
- Update actions in workflows to current versions using NodeJS v20
- Minor revisions to README
- Earlier versions of NodeJS are now deprecated
- Improve the readability
=> Update actions used by GitHub workflows

README.md
- Update `README.md` as was intended in #910 
- Forgot that it does not automatically build in this repo, and #910 only updated the source YAML
=> Stylistic clean-up of README

rootfs/usr/local/bin/boot
- Fix default app name in installation output
- Should have been part of #972
=> Fix default app name in installation output
